#!/bin/bash --login

#SBATCH --time=24:00:00   # walltime
#SBATCH --ntasks=80   # number of processor cores (i.e. tasks)
#SBATCH --nodes=1   # number of nodes
#SBATCH --mem=200G   # memory per CPU core
#SBATCH --gpus=0  # num gpus
#SBATCH --qos=cs

# Set the max number of threads to use for programs using OpenMP. Should be <= ppn. Does nothing if the program doesn't use OpenMP.
export OMP_NUM_THREADS=$SLURM_CPUS_ON_NODE

# LOAD MODULES, INSERT CODE, AND RUN YOUR PROGRAMS HERE
mamba activate nhl_pred
python ~/NHL_Win_Predictor/catboost_train.py --team "$1"